# Generated by Django 3.2.7 on 2021-09-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=45)),
                ('genero', models.CharField(max_length=45)),
                ('qtd_paginas', models.IntegerField()),
            ],
        ),
    ]
