# Generated by Django 3.2.7 on 2021-09-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ('titulo',)},
        ),
        migrations.AlterField(
            model_name='livro',
            name='qtd_paginas',
            field=models.IntegerField(verbose_name='Número de páginas'),
        ),
    ]
